/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tEG8oO7neZP
 */
import { CardContent, Card } from "@/components/ui/card"

  export const Weather = ({ temperature, unit, description }: {
  temperature: String, unit: String, description: String}) => {
  return (
    <div className="flex items-center justify-center w-full p-4">
      <Card className="w-full max-w-sm">
        <CardContent className="p-6">
          <div className="flex items-center gap-4">
            <SunIcon className="text-5xl w-10 h-10" />
            <div className="flex flex-col text-3xl font-semibold leading-none">
              <span className="text-2xl font-medium leading-none">Current</span>
              <span className="text-4xl font-extrabold">{temperature}°{unit}</span>
            </div>
          </div>
          <p className="mt-4 text-gray-500 dark:text-gray-400">
            {description}
          </p>
        </CardContent>
      </Card>
    </div>
  )
}


function SunIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
